import lib = libsimbody%lib{SimTKmath}

./: tests/hxx{*} # Ensure any headers are distributed

# Note: The *ExplicitEuler* tests are very slow.
#
# @@ TODO Re-enable the *ExplicitEuler* tests.
#
for t: tests/cxx{* -*ExplicitEuler*}
  ./: exe{$name($t)}: $t testscript $lib

exe{TestSpline}: test.cleanups = '&simtk_splinefitter*.csv'
exe{CMAESTest}:  test.cleanups = '&actparcmaes.par' \
                                 '&errcmaes.err'
