import lib = libsimbody%lib{SimTKmath}

./: tests/hxx{*} # Ensure any headers are distributed

# Note: Exclude TestBicubicSurface because it includes a header from the src/
#       directory which is not installed and thus test-installed fails on
#       CI. Turning these into unit tests would fix it but all of the other
#       tests use only the public API so it seems like the overall intention
#       is for these to be integration tests. Should probably report this
#       upstream.
#
for t: tests/cxx{* -TestBicubicSurface}
  ./: exe{$name($t)}: $t testscript $lib

exe{TestSpline}: test.cleanups = '&simtk_splinefitter*.csv'
exe{CMAESTest}:  test.cleanups = '&actparcmaes.par' \
                                 '&errcmaes.err'
