intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

# Headers and source files.
#
./: lib{SimTKcommon}: SimTKcommon/hxx{**} \
                      SimTKcommon/cxx{** -tests/**}

./: lib{SimTKmath}: SimTKmath/hxx{**}                 \
                    SimTKmath/cxx{** -**tests/*}      \
                    SimTKmath/{h c}{** -**tests/*}

./: lib{SimTKsimbody}: Simbody/hxx{** -Visualizer/simbody-visualizer/**} \
                       Simbody/cxx{** -Visualizer/simbody-visualizer/** -tests/**}

sys_libs =
if ($cxx.target.class != 'windows')
{
  sys_libs += -llapack -ldl -lm

  if ($cxx.target.class != 'macos')
    sys_libs += -pthread -lrt
}

lib{SimTKcommon SimTKmath SimTKsimbody}: cxx.libs += $sys_libs

lib{SimTKmath}: lib{SimTKcommon}
lib{SimTKsimbody}: lib{SimTKcommon SimTKmath}

# Build options: SimTKcommon
#
SimTKcommon/obj{*}:                                                             \
  cxx.poptions += "-I$src_base/include"                                         \
                  "-I$src_base/BigMatrix/include"                               \
                  "-I$src_base/Geometry/include"                                \
                  "-I$src_base/Mechanics/include"                               \
                  "-I$src_base/Polynomial/include"                              \
                  "-I$src_base/Random/include"                                  \
                  "-I$src_base/Scalar/include"                                  \
                  "-I$src_base/Simulation/include"                              \
                  "-I$src_base/SmallMatrix/include"                             \
                  -DSimTK_SimTKCOMMON_AUTHORS=\"Michael.Sherman_Peter.Eastman\" \
                  -DSimTK_SimTKCOMMON_COPYRIGHT_YEARS=\"2005-10\"               \
                  -DSimTK_SimTKCOMMON_LIBRARY_NAME=SimTKcommon                  \
                  -DSimTK_SimTKCOMMON_MAJOR_VERSION="$version.major"            \
                  -DSimTK_SimTKCOMMON_MINOR_VERSION="$version.minor"            \
                  -DSimTK_SimTKCOMMON_PATCH_VERSION="$version.patch"

SimTKcommon/objs{*}: cxx.poptions += -DSimTK_SimTKCOMMON_BUILDING_SHARED_LIBRARY        \
                                     -DSimTKcommon_EXPORTS

SimTKcommon/obja{*}: cxx.poptions += -DSimTK_SimTKCOMMON_BUILDING_STATIC_LIBRARY

# Build options: SimTKmath
#
SimTKmath/obj{*}:                                                               \
  cc.poptions += "-I$src_base/include"                                          \
                 "-I$src_base/LinearAlgebra/include"                            \
                 "-I$src_base/Integrators/include"                              \
                 "-I$src_base/Optimizers/include"                               \
                 "-I$src_base/Geometry/include"                                 \
                 "-I$src_base/Integrators/src/CPodes/sundials/include"          \
                 -DSimTK_SIMMATH_AUTHORS=\"Jack.Middleton_Michael.Sherman\"     \
                 -DSimTK_SIMMATH_COPYRIGHT_YEARS=\"2005-10\"                    \
                 -DSimTK_SIMMATH_LIBRARY_NAME=SimTKmath                         \
                 -DSimTK_SIMMATH_MAJOR_VERSION="$version.major"                 \
                 -DSimTK_SIMMATH_MINOR_VERSION="$version.minor"                 \
                 -DSimTK_SIMMATH_PATCH_VERSION="$version.patch"

SimTKmath/objs{*}: cc.poptions += -DSimTK_SIMMATH_BUILDING_SHARED_LIBRARY       \
                                  -DSimTKmath_EXPORTS

SimTKmath/obja{*}: cc.poptions += -DSimTK_SIMMATH_BUILDING_STATIC_LIBRARY

# -DSIMBODY_PATH_FROM_LIBDIR_TO_VIZ_DIR=\"../libexec/simbody\"
# -DSIMBODY_VISUALIZER_INSTALL_DIR=\"/usr/local/libexec/simbody/\"
# -DSIMBODY_VISUALIZER_REL_INSTALL_DIR=\"libexec/simbody/\"
# -DSimTK_SIMBODY_AUTHORS=\"Michael.Sherman_Peter.Eastman\"
# -DSimTK_SIMBODY_BUILDING_SHARED_LIBRARY
# -DSimTK_SIMBODY_COPYRIGHT_YEARS=\"2005-20\"
# -DSimTK_SIMBODY_LIBRARY_NAME=SimTKsimbody
# -DSimTK_SIMBODY_MAJOR_VERSION=3
# -DSimTK_SIMBODY_MINOR_VERSION=8
# -DSimTK_SIMBODY_PATCH_VERSION=0
# -DSimTKsimbody_EXPORTS

# Build options: SimTKsimbody
#
# Note that the various path/directory macros are only used to launch the
# Visualizer executable which is not supported so just use fake values for the
# sake of simplicity (and to flush out problems early).
#
Simbody/obj{*}:                                                                 \
  cxx.poptions += "-I$src_base/include"                                         \
                  "-I$src_base/Visualizer/include"                              \
                  -DSimTK_SIMBODY_AUTHORS=\"Michael.Sherman_Peter.Eastman\"     \
                  -DSimTK_SIMBODY_COPYRIGHT_YEARS=\"2005-20\"                   \
                  -DSimTK_SIMBODY_LIBRARY_NAME=SimTKsimbody                     \
                  -DSimTK_SIMBODY_MAJOR_VERSION="$version.major"                \
                  -DSimTK_SIMBODY_MINOR_VERSION="$version.minor"                \
                  -DSimTK_SIMBODY_PATCH_VERSION="$version.patch"                \
                  -DSIMBODY_PATH_FROM_LIBDIR_TO_VIZ_DIR="\"nonexistent_dir\""   \
                  -DSIMBODY_VISUALIZER_INSTALL_DIR="\"nonexistent_dir\""        \
                  -DSIMBODY_VISUALIZER_REL_INSTALL_DIR="\"nonexistent_dir\""

Simbody/objs{*}: cxx.poptions += -DSimTK_SIMBODY_BUILDING_SHARED_LIBRARY        \
                                 -DSimTKsimbody_EXPORTS

Simbody/obja{*}: cxx.poptions += -DSimTK_SIMBODY_BUILDING_STATIC_LIBRARY

# Export options: SimTKcommon
#
lib{SimTKcommon}:
{
  cxx.export.poptions = "-I$src_base/SimTKcommon/include"               \
                        "-I$src_base/SimTKcommon/BigMatrix/include"     \
                        "-I$src_base/SimTKcommon/Geometry/include"      \
                        "-I$src_base/SimTKcommon/Mechanics/include"     \
                        "-I$src_base/SimTKcommon/Polynomial/include"    \
                        "-I$src_base/SimTKcommon/Random/include"        \
                        "-I$src_base/SimTKcommon/Scalar/include"        \
                        "-I$src_base/SimTKcommon/Simulation/include"    \
                        "-I$src_base/SimTKcommon/SmallMatrix/include"

  cxx.export.libs = $intf_libs
}

if ($cxx.target.class != 'windows')
  lib{SimTKcommon}: cxx.export.libs += $sys_libs

# Export options: SimTKmath
#
lib{SimTKmath}:
{
  cxx.export.poptions = "-I$src_base/SimTKmath/include"                 \
                        "-I$src_base/SimTKmath/LinearAlgebra/include"   \
                        "-I$src_base/SimTKmath/Integrators/include"     \
                        "-I$src_base/SimTKmath/Optimizers/include"      \
                        "-I$src_base/SimTKmath/Geometry/include"

  cxx.export.libs = $intf_libs lib{SimTKcommon}
}

# Export options: SimTKsimbody
#
lib{SimTKsimbody}:
{
  cxx.export.poptions = "-I$src_base/Simbody/include"   \
                        "-I$src_base/Simbody/Visualizer/include"

  cxx.export.libs = $intf_libs lib{SimTKcommon SimTKmath}
}

# Export options: All libraries
#
liba{SimTKcommon SimTKmath SimTKsimbody}: \
  cxx.export.poptions += -DSimTK_USE_STATIC_LIBRARIES

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{SimTKcommon SimTKmath SimTKsimbody}: \
    bin.lib.version = "-$version.project_id"
else
  lib{SimTKcommon SimTKmath SimTKsimbody}: \
    bin.lib.version = "-$version.major.$version.minor"

# Install into the libsimbody/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libsimbody/
  install.subdirs = true
}
